/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei/native'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Male_body: THREE.SkinnedMesh
    Male_hair: THREE.SkinnedMesh
    Male_shoes: THREE.SkinnedMesh
    Male_shorts: THREE.SkinnedMesh
    Male_tshirt: THREE.SkinnedMesh
    Female_body: THREE.SkinnedMesh
    Female_hair: THREE.SkinnedMesh
    Female_shoes: THREE.SkinnedMesh
    Female_shorts: THREE.SkinnedMesh
    Female_tshirt: THREE.SkinnedMesh
    Hips: THREE.Bone
    Hips_1: THREE.Bone
  }
  materials: {
    Male: THREE.MeshStandardMaterial
    Female: THREE.MeshStandardMaterial
  }
}


export default function Avatar(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF(require('../../models/avatar_complete.glb')) as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Male_Armature">
          <skinnedMesh
            name="Male_body"
            geometry={nodes.Male_body.geometry}
            material={materials.Male}
            skeleton={nodes.Male_body.skeleton}
          />
          <skinnedMesh
            name="Male_hair"
            geometry={nodes.Male_hair.geometry}
            material={materials.Male}
            skeleton={nodes.Male_hair.skeleton}
          />
          <skinnedMesh
            name="Male_shoes"
            geometry={nodes.Male_shoes.geometry}
            material={materials.Male}
            skeleton={nodes.Male_shoes.skeleton}
          />
          <skinnedMesh
            name="Male_shorts"
            geometry={nodes.Male_shorts.geometry}
            material={materials.Male}
            skeleton={nodes.Male_shorts.skeleton}
          />
          <skinnedMesh
            name="Male_tshirt"
            geometry={nodes.Male_tshirt.geometry}
            material={materials.Male}
            skeleton={nodes.Male_tshirt.skeleton}
          />
          <primitive object={nodes.Hips} />
        </group>
        <group name="Female_Armature">
          <skinnedMesh
            name="Female_body"
            geometry={nodes.Female_body.geometry}
            material={materials.Female}
            skeleton={nodes.Female_body.skeleton}
          />
          <skinnedMesh
            name="Female_hair"
            geometry={nodes.Female_hair.geometry}
            material={materials.Female}
            skeleton={nodes.Female_hair.skeleton}
          />
          <skinnedMesh
            name="Female_shoes"
            geometry={nodes.Female_shoes.geometry}
            material={materials.Female}
            skeleton={nodes.Female_shoes.skeleton}
          />
          <skinnedMesh
            name="Female_shorts"
            geometry={nodes.Female_shorts.geometry}
            material={materials.Female}
            skeleton={nodes.Female_shorts.skeleton}
          />
          <skinnedMesh
            name="Female_tshirt"
            geometry={nodes.Female_tshirt.geometry}
            material={materials.Female}
            skeleton={nodes.Female_tshirt.skeleton}
          />
          <primitive object={nodes.Hips_1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(require('../../models/avatar_complete.glb'));