/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useTexture, useAnimations } from '@react-three/drei/native'
import { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    Female_body: THREE.SkinnedMesh
    Female_hair: THREE.SkinnedMesh
    Female_shoes: THREE.SkinnedMesh
    Female_shorts: THREE.SkinnedMesh
    Female_tshirt: THREE.SkinnedMesh
    Hips: THREE.Bone
  }
  materials: {
    Female: THREE.MeshStandardMaterial
  }
}


export default function Avatar(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const mesh = useRef<THREE.Mesh>();
  const { nodes, materials, animations } = useGLTF(require('../../models/female_avatar.glb')) as GLTFResult
  const { actions } = useAnimations(animations, group);
  // Manually load textures if needed
  const femaleTexture = useTexture(require('../../models/Female_texture.png'));
  const maleTexture = useTexture(require('../../models/Male_texture.png'));

  useFrame(({ clock }) => {
    if (mesh.current) {
      mesh.current.rotation.x = Math.sin(clock.getElapsedTime()); // Rotate for debugging
      mesh.current.rotation.y = Math.sin(clock.getElapsedTime()); // Rotate for debugging
      mesh.current.rotation.z = Math.sin(clock.getElapsedTime()); // Rotate for debugging
    }
  })

  // Ensure materials are correctly assigned
  //materials.Female.map = femaleTexture;
  //materials.Female.map = maleTexture;

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Female_Armature">
          <skinnedMesh
            name="Female_body"
            geometry={nodes.Female_body.geometry}
            material={materials.Female}
            skeleton={nodes.Female_body.skeleton}
          />
          <skinnedMesh
            name="Female_hair"
            geometry={nodes.Female_hair.geometry}
            material={materials.Female}
            skeleton={nodes.Female_hair.skeleton}
          />
          <skinnedMesh
            name="Female_shoes"
            geometry={nodes.Female_shoes.geometry}
            material={materials.Female}
            skeleton={nodes.Female_shoes.skeleton}
          />
          <skinnedMesh
            name="Female_shorts"
            geometry={nodes.Female_shorts.geometry}
            material={materials.Female}
            skeleton={nodes.Female_shorts.skeleton}
          />
          <skinnedMesh
            name="Female_tshirt"
            geometry={nodes.Female_tshirt.geometry}
            material={materials.Female}
            skeleton={nodes.Female_tshirt.skeleton}
          />
          <primitive ref={mesh} object={nodes.Hips} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(require('../../models/female_avatar.glb'));